name: Fisheye Video Conference System

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    outputs:
      tag_name: ${{ steps.generate_tag.outputs.tag_name }}

    steps:
      - name: Checkout repository (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - name: Checkout Private Repository
        shell: pwsh
        run: |
          git clone --single-branch --depth 1 --branch release https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/perseverance-tech-tw/video-conference-using-fisheye.git video-conference-using-fisheye
          cd video-conference-using-fisheye
          git fetch origin release --depth 1
          git reset --hard origin/release    # pastikan benar-benar di HEAD terbaru
          Write-Host "Listing contents of the cloned repository:"
          Get-ChildItem -Force -Recurse
          
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Generate Tag Name from latest Git tag
        id: generate_tag
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags --prune
          latest_tag=$(git tag --sort=-v:refname | grep '^v1\.2\.' | head -n 1 || true)
          if [ -z "$latest_tag" ]; then
            next_tag="v1.2.0"
          else
            patch=${latest_tag##v1.2.}
            next_patch=$((patch + 1))
            next_tag="v1.2.$next_patch"
          fi
          echo "TAG_NAME=$next_tag" >> "$GITHUB_ENV"
          echo "tag_name=$next_tag" >> "$GITHUB_OUTPUT"
        
      - name: Update version.txt
        shell: bash
        run: echo "${{ env.TAG_NAME }}" > version.txt
        working-directory: video-conference-using-fisheye

      - name: Replace version placeholder in ISS file
        shell: bash
        run: |
        
          # Verify the dist directory and setup_script.iss file exist before replacing version
          if [ ! -f "dist/setup_script.iss" ]; then
            echo "setup_script.iss not found in dist/"
            exit 1
          fi

          # Replace version placeholder in setup_script.iss with the correct TAG_NAME
          sed -i "s/__VERSION__/${{ env.TAG_NAME }}/g" dist/setup_script.iss
          
        working-directory: video-conference-using-fisheye

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          
        working-directory: video-conference-using-fisheye

      - name: Build with PyInstaller
        shell: bash
        run: pyinstaller --clean video-conference-using-fisheye.spec
        working-directory: video-conference-using-fisheye

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup -y
        working-directory: video-conference-using-fisheye
        
      - name: Build Installer
        shell: cmd
        run: 
          iscc dist\setup_script.iss
        working-directory: video-conference-using-fisheye

      - name: Get previous tag (robust)
        id: previoustag
        shell: bash
        run: |
          set -euo pipefail
          if git describe --tags --abbrev=0 HEAD^ >/dev/null 2>&1; then
            prev=$(git describe --tags --abbrev=0 HEAD^)

          else
            prev=""
          fi
          echo "tag=$prev" >> "$GITHUB_OUTPUT"
        working-directory: video-conference-using-fisheye
          
      - name: Generate changelog (robust)
        id: changelog
        shell: bash
        run: |
          set -euo pipefail
          
          # Generate the changelog using git log
          if [ -n "${{ steps.previoustag.outputs.tag }}" ]; then
            log_output=$(git log ${{ steps.previoustag.outputs.tag }}..HEAD --pretty=format:"- %s (%h)")
          else
            log_output=$(git log --pretty=format:"- %s (%h)")
          fi
      
          # Replace newlines with spaces or another delimiter to format as a single string
          log_output=$(echo "$log_output" | tr '\n' ' ')

          # Ensure there is no leading/trailing space
          log_output=$(echo "$log_output" | xargs)
      
          # Output the changelog to GITHUB_OUTPUT
          echo "log=$log_output" >> "$GITHUB_OUTPUT"

        working-directory: video-conference-using-fisheye
        
      - name: Upload Windows Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Pakai glob agar aman jika nama file installer berbeda tipis
          files: |
            video-conference-using-fisheye/dist/Output/*Fisheye*${{ env.TAG_NAME }}*.exe
          tag_name: ${{ env.TAG_NAME }}
          body: |
            Fisheye Video Conference System ${{ env.TAG_NAME }}
            ${{ steps.changelog.outputs.log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  build-linux:
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
      - name: Checkout repository (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Private Repository
        run: |
          # Clone the private repository
          git clone --branch release https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/perseverance-tech-tw/video-conference-using-fisheye.git video-conference-using-fisheye
          
          # Change to the directory of the cloned repository
          cd video-conference-using-fisheye
          
          # Optionally, verify that the repository is cloned
          echo "Listing contents of the cloned repository:"
          ls -l

      - name: Set TAG_NAME from Windows job
        shell: bash
        run: echo "TAG_NAME=${{ needs.build-windows.outputs.tag_name }}" >> "$GITHUB_ENV"
        working-directory: video-conference-using-fisheye
        
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
        
      - name: Update version.txt
        shell: bash
        run: echo "${{ env.TAG_NAME }}" > version.txt
        working-directory: video-conference-using-fisheye
        
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
        working-directory: video-conference-using-fisheye
        
      - name: Create dist/linux folder
        shell: bash
        run: mkdir -p dist/linux
        working-directory: video-conference-using-fisheye
        
      - name: Build with PyInstaller (Linux)
        shell: bash
        run: pyinstaller --clean --distpath dist/linux video-conference-using-fisheye.spec
        working-directory: video-conference-using-fisheye
        
      - name: Copy install.sh and uninstall.sh into dist/linux folder
        shell: bash
        run: |
          set -euo pipefail
          appdir="dist/linux/FisheyeVideoConferenceSystem"
          if [ ! -d "$appdir" ]; then
            echo "Explicit appdir not found, searching…"
            # Try to find a PyInstaller app dir that contains an executable
            appdir=$(find dist/linux -maxdepth 1 -type d -not -path 'dist/linux' | head -n1 || true)
          fi
          if [ -z "${appdir:-}" ] || [ ! -d "$appdir" ]; then
            echo "ERROR: Could not find app output folder under dist/linux"
            ls -la dist/linux || true
            exit 1
          fi
          echo "App directory detected: $appdir"
          ls -la "$appdir"

          cp dist/install.sh "$appdir"/
          cp dist/uninstall.sh "$appdir"/
          chmod +x "$appdir"/install.sh "$appdir"/uninstall.sh
        working-directory: video-conference-using-fisheye
        
      - name: Install p7zip
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y p7zip-full
        working-directory: video-conference-using-fisheye
        
      - name: Compress to .7z (LZMA2) and self-test
        shell: bash
        run: |
          set -euo pipefail
          cd dist/linux

          appdir=$(find . -maxdepth 1 -type d -not -path '.' | head -n1)
          echo "Zipping folder: $appdir"
          out="../FisheyeVideoConferenceSystem-${TAG_NAME}-linux.7z"
          # Use LZMA2 (default), maximum compression, solid blocks
          7z a -t7z -m0=lzma2 -mx=9 -ms=on "$out" "$appdir"

          echo "Archive created:"
          ls -lh "$out"

          echo "Testing archive integrity…"
          7z t "$out"
        working-directory: video-conference-using-fisheye
        
      - name: Get previous tag (robust)
        id: previoustag
        shell: bash
        run: |
          set -euo pipefail
          if git describe --tags --abbrev=0 HEAD^ >/dev/null 2>&1; then
            prev=$(git describe --tags --abbrev=0 HEAD^)
          else
            prev=""
          fi
          echo "tag=$prev" >> "$GITHUB_OUTPUT"
        working-directory: video-conference-using-fisheye
        
      - name: Upload Linux Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            video-conference-using-fisheye/dist/FisheyeVideoConferenceSystem-${{ env.TAG_NAME }}-linux.7z
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
